apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: ingress-nginx
  
spec:
  type: ClusterIP
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8001
      #nodePort: 32220